config/urls.py
"""
Our sitewide URLs
"""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from ryhom.core.views import Error404View

urlpatterns = [
    path('', include('ryhom.core.urls', namespace='core')),
    path('u/', include('ryhom.accounts.urls', namespace='accounts')),
    path('cat/', include('ryhom.categories.urls', namespace='categories')),
    path('tag/', include('ryhom.tags.urls', namespace='tags')),
    path('article/', include('ryhom.articles.urls', namespace='articles')),
    path('post/', include('ryhom.microposts.urls', namespace='microposts')),

    path('/ckeditor/', include('ckeditor_uploader.urls')),
]


# Enable the use of Django admin if "IS_ADMIN_ENABLED" variable is set to true
# If it's false, the Django admin login page shows a 404 page
if settings.IS_ADMIN_ENABLED:
    urlpatterns.append(path('site/ryhom/admin/', admin.site.urls))

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = Error404View.as_view()

ryhom/accounts/urls.py
from django.urls import path

from .views import (AccountSettingsView, ActivateAccountView, ChangeEmailView,
                    ChangePasswordView, LoginUserView, LogoutUserView,
                    RegisterView, ResendActivationEmailView,
                    ResetPasswordConfirmationView, ResetPasswordDoneView,
                    ResetPasswordMessageView, ResetPasswordView, UserPostsView,
                    UserProfileView)

app_name = 'accounts'

urlpatterns = [
    path(
        'auth/create-account',
        RegisterView.as_view(),
        name='create_account'
    ),
    path(
        'auth/activate/<uidb64>/<token>',
        ActivateAccountView.as_view(),
        name='activate'
    ),
    path(
        'auth/resend-activitation-email',
        ResendActivationEmailView.as_view(),
        name='resend_activation_email'
    ),
    path(
        'auth/login',
        LoginUserView.as_view(),
        name='login'
    ),
    path(
        'auth/logout',
        LogoutUserView.as_view(),
        name='logout'
    ),
    path(
        'auth/password-reset',
        ResetPasswordView.as_view(),
        name='password_reset'
    ),
    path(
        'auth/password-reset/message',
        ResetPasswordMessageView.as_view(),
        name='password_reset_message',
    ),
    path(
        'auth/password-reset-confirm/<uidb64>/<token>',
        ResetPasswordConfirmationView.as_view(),
        name='password_reset_confirm'
    ),
    path(
        'auth/password-reset/done',
        ResetPasswordDoneView.as_view(),
        name='password_reset_done',
    ),

    path(
        'account/settings',
        AccountSettingsView.as_view(),
        name='account_settings'
    ),
    path(
        'account/my-posts',
        UserPostsView.as_view(),
        name='my_posts'
    ),
    path(
        '<slug:user_profile_slug>',
        UserProfileView.as_view(),
        name='user_profile'
    ),

    path(
        'account/settings/password/change',
        ChangePasswordView.as_view(),
        name='change_password'
    ),
    path(
        'account/settings/email/change',
        ChangeEmailView.as_view(),
        name='change_email'
    ),
]

ryhom/articles/urls.py
from django.urls import path

from .views import (AddArticleView, AddRemoveArticleCommentLike,
                    ArticleDetailView, DeleteArticleView, EditArticleView)

app_name = 'articles'

urlpatterns = [
    path(
        'add-article',
        AddArticleView.as_view(),
        name='add_article'
    ),
    path(
        'edit-article/<uuid:article_uuid>',
        EditArticleView.as_view(),
        name='edit_article'
    ),
    path(
        'delete-article/<uuid:article_uuid>',
        DeleteArticleView.as_view(),
        name='delete_article'
    ),

    path(
        '<slug:article_slug>',
        ArticleDetailView.as_view(),
        name='article_detail'
    ),
    path(
        '<int:article_pk>/comment/<int:pk>/like',
        AddRemoveArticleCommentLike.as_view(),
        name='article_comment_like_unlike'
    ),
]

ryhom/core/urls.py
from django.urls import path

from .views import IndexView, user_profile_redirect

app_name = 'core'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('profile-redirect', user_profile_redirect),
]

ryhom/tags/urls.py
from django.urls import path

from .views import ArticlesByTagListView, MicropostsByTagListView

app_name = 'tags'

urlpatterns = [
    path(
        'articles/<slug:tag_slug>',
        ArticlesByTagListView.as_view(),
        name='articles_by_tag'
    ),
    path(
        'microposts/<slug:tag_slug>',
        MicropostsByTagListView.as_view(),
        name='microposts_by_tag'
    ),
]

ryhom/core/forms.py
from datetime import timezone

from django import forms
from django.contrib.auth.hashers import check_password
from django.forms import ModelForm
from django.utils import timezone
from ryhom.accounts.models import Account


class ConfirmPasswordForm(ModelForm):
    confirm_password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = Account
        fields = ('confirm_password',)

    def clean(self):
        cleaned_data = super(ConfirmPasswordForm, self).clean()
        confirm_password = cleaned_data.get('confirm_password')
        if not check_password(confirm_password, self.instance.password):
            self.add_error('confirm_password', 'Password does not match.')

    def save(self, commit=True):
        user = super(ConfirmPasswordForm, self).save(commit)
        user.last_login = timezone.now()
        if commit:
            user.save()
        return user

ryhom/accounts/views.py
import socket
from itertools import chain
from operator import attrgetter
from smtplib import SMTPException

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.utils.encoding import force_str
from django.utils.http import urlsafe_base64_decode
from django.views.generic import DetailView, FormView, ListView, View
from django.views.generic.edit import CreateView, UpdateView

from ryhom.articles.models import Article, ArticleComment
from ryhom.core.decorators import confirm_password
from ryhom.core.viewmixins import RedirectAuthenticatedUserMixin
from ryhom.microposts.models import Micropost, MicropostComment

from .forms import (AccountSettingsForm, ChangeEmailForm, ChangePasswordForm,
                    ForgotPasswordForm, LoginForm, RegisterForm,
                    ResendActivationEmailForm, SetNewPasswordForm)
from .models import Account
from .tokens import account_token_generator
from .utils import send_registration_confirm_email

# A list of decorators including our custom decorator -> confirm_password
# that requires the user to insert their password again if there's more
# than, 30 minutes for example, from their last login if they are
# accessing a view with this decorator.
decorators = [login_required, confirm_password]


class RegisterView(RedirectAuthenticatedUserMixin, CreateView):
    form_class = RegisterForm
    template_name = 'accounts/create-account.html'
    success_url = reverse_lazy('accounts:create_account')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False # Deactivate account till it is confirmed
        user.save()

        to_email = form.cleaned_data['email']

        # For all possible send_mail (SMTPException) exceptions...
        # https://docs.python.org/3/library/smtplib.html#smtplib.SMTPException
        try:
            send_registration_confirm_email(self, user, to_email)
            success_message = (f'An account has been created! We\'ve sent \
                                a verification link to <b>{to_email}</b>. \
                                Click it to activate your account!')
            messages.success(self.request, success_message)
        except (SMTPException, socket.gaierror):
            error_message = 'There was an error connecting to the email \
                            server, this is likely our fault. Please try \
                            creating an account later.'
            messages.error(self.request, error_message)

        return super().form_valid(form)


    def form_invalid(self, form):
        error_message = (
            'Error creating the user, please fix the errors below...'
        )
        messages.error(self.request, error_message)
        return super().form_invalid(form)


class ResendActivationEmailView(RedirectAuthenticatedUserMixin, FormView):
    template_name = 'accounts/resend-verification-email.html'
    form_class = ResendActivationEmailForm
    success_url = reverse_lazy('accounts:resend_activation_email')

    def form_valid(self, form):
        email_input = form.cleaned_data['email']
        if Account.objects.filter(email=email_input).exists():
            user = Account.objects.get(email=email_input)
            if not user.is_active:
                self.send_email_to_user(user, email_input)
            else:
                error_message = (
                    'This account has already been activated!'
                )
                messages.warning(self.request, error_message)
        else:
            error_message = (
                'Account with this email doesn\'t exist'
            )
            messages.warning(self.request, error_message)

        return super().form_valid(form)

    def send_email_to_user(self, user, to_email):
        try:
            send_registration_confirm_email(self, user, to_email)
            success_message = (f'A new verification link has been sent to \
                                <b>{to_email}</b>. Click it to activate \
                                your account!')
            response = messages.success(self.request, success_message)
        except (SMTPException, socket.gaierror):
            error_message = 'There was an error connecting to the email \
                            server, this is likely our fault. Please try \
                            resending the verification email later.'
            response = messages.error(self.request, error_message)
        return response


class ActivateAccountView(View):
    def get(self, request, uidb64, token,
            backend='django.contrib.auth.backends.ModelBackend'):
        try:
            uid = force_str(urlsafe_base64_decode(uidb64))
            user = Account.objects.get(pk=uid)
        except (TypeError,
                ValueError,
                OverflowError,
                Account.DoesNotExist):

            user = None

        if user is not None and account_token_generator.check_token(
            user, token):

            user.is_active = True
            user.save()

            if request.user.is_authenticated:
                logout(request)

            login(
                request,
                user,
                backend
            )
            messages.success(request, 'Your email address has been verfied!')
            return redirect(settings.LOGIN_REDIRECT_URL)
        else:
            messages.warning(request, ('The confirmation link was invalid, \
                                possibly because it has already been used.'))
            return redirect(settings.LOGIN_URL)


class LoginUserView(LoginView):
    authentication_form = LoginForm
    template_name = 'accounts/login.html'
    redirect_authenticated_user = settings.LOGIN_REDIRECT_URL


class LogoutUserView(LogoutView):
    def get_next_page(self):
        next_page = super(LogoutUserView, self).get_next_page()
        messages.add_message(
            self.request, messages.SUCCESS,
            "You've successfully logged out!"
        )
        return next_page


@method_decorator(decorators, name='dispatch')
class AccountSettingsView(UpdateView):
    template_name = 'accounts/account-settings.html'
    form_class = AccountSettingsForm
    success_url = reverse_lazy('accounts:account_settings')

    def get_object(self):
        return self.request.user

    def form_valid(self, form):
        messages.success(self.request,
            'Your changes were successfully saved!'
        )
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request,
                    'Unable to make the changes, \
                    fix the errors below and try again.'
        )
        return self.render_to_response(self.get_context_data(form=form))


class UserProfileView(DetailView):
    model = Account
    template_name = 'accounts/user-profile.html'

    def get_object(self):
        self.user = get_object_or_404(
            Account, slug=self.kwargs['user_profile_slug']
        )
        return self.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        user_articles = Article.articles.by_author(
            self.user).published().order_by('-modified')

        user_articles_amount = user_articles.count()

        user_microposts = Micropost.microposts.by_author(
            self.user).published().order_by('-created')

        user_microposts_amount = user_microposts.count()

        # Perhaps here we should also have [:10] after the query???
        user_article_comments = ArticleComment.article_comments.user_comments(self.user)

        user_micropost_comments = MicropostComment.micropost_comments.user_comments(self.user)

        # Let's combine all user comment querysets into one
        # collection of objects --> (WE CAN CHAIN EVEN MORE IF WE WANT TO!)
        # and order them by their creation date + let's show newest comments
        # first with reverse=True
        user_comments = sorted(
            chain(user_article_comments, user_micropost_comments),
            key=attrgetter('created'), reverse=True
        )[:10]

        paginator = Paginator(user_articles, 10)
        page = self.request.GET.get('user-articles-page')
        try:
            user_articles = paginator.page(page)
        except PageNotAnInteger:
            user_articles = paginator.page(1)
        except EmptyPage:
            user_articles = paginator.page(paginator.num_pages)

        paginator = Paginator(user_microposts, 10)
        page = self.request.GET.get('user-microposts-page')
        try:
            user_microposts = paginator.page(page)
        except PageNotAnInteger:
            user_microposts = paginator.page(1)
        except EmptyPage:
            user_microposts = paginator.page(paginator.num_pages)

        context['user_articles'] = user_articles
        context['user_articles_amount'] = user_articles_amount

        context['user_microposts'] = user_microposts
        context['user_microposts_amount'] = user_microposts_amount

        context['user_comments'] = user_comments

        return context


class UserPostsView(LoginRequiredMixin, ListView):

ryhom/categories/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import ListView
from ryhom.articles.models import Article

from .models import Category


class CategoryDetailView(ListView):
    model = Category
    context_object_name = 'articles_in_category'
    template_name = 'categories/category-page.html'
    paginate_by = 2

    def get_queryset(self):
        self.category = get_object_or_404(Category, slug=self.kwargs['category_slug'])
        queryset = Article.articles.published().by_category(self.category)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(CategoryDetailView, self).get_context_data(**kwargs)
        context['category'] = self.category
        return context

ryhom/core/views.py
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import redirect
from django.views import View
from django.views.generic.base import TemplateView
from django.views.generic.edit import UpdateView

from .forms import ConfirmPasswordForm


class IndexView(TemplateView):
    template_name = 'index.html'


class ConfirmPasswordView(UpdateView):
    form_class = ConfirmPasswordForm
    template_name = 'continue-session.html'

    def get_object(self):
        return self.request.user

    def get_success_url(self):
        return self.request.get_full_path()


class Error404View(View):
    def index(self):
        raise Http404


@login_required
def user_profile_redirect(request):
    """
    Used as a dynamic redirect to user's personal profile, because the
    user profile URL requires a slug kwarg, hence, a custom redirect

    settings.py --> LOGIN_REDIRECT_URL
    """
    slug = request.user.slug
    return redirect('accounts:user_profile', user_profile_slug=slug)

ryhom/templates/articles/add-article.html
{% extends 'boilerplate.html' %}

{% block title %}Add An Article{% endblock title %}

{% block navbar %}
  {% include 'navbar.html' %}
{% endblock navbar %}

{% block content %}
  <h1>Add An Article...</h1>

  {% if messages %}
    {% for message in messages %}
      <p>{{ message | safe }}</p>
    {% endfor %}
  {% endif %}

  <form action="" enctype="multipart/form-data" method="POST">
    {% csrf_token %}

    {% for error in form.non_field_errors %}
      <p>{{ error }}</p>
    {% endfor %}

    {{ form.media }}

    <p>{{ form.title.label_tag }}</p>
    {{ form.title }}
    <p><em>{{ form.title.help_text }}</em></p>
    {{ form.title.errors }}

    <p>{{ form.summary.label_tag }}</p>
    {{ form.summary }}
    <p><em>{{ form.summary.help_text }}</em></p>
    {{ form.summary.errors }}

    <p>{{ form.image.label_tag }}</p>
    {{ form.image }}
    <p><em>{{ form.image.help_text }}</em></p>
    {{ form.image.errors }}

    <p>{{ form.image_credit.label_tag }}</p>
    {{ form.image_credit }}
    <p><em>{{ form.image_credit.help_text }}</em></p>
    {{ form.image_credit.errors }}

    <p>{{ form.content.label_tag }}</p>
    {{ form.content }}
    <p><em>{{ form.content.help_text }}</em></p>
    {{ form.content.errors }}

    <button name="save_for_later" type="submit">Save</button>

    <button name="submit_for_review" type="submit">Submit For Review</button>

  </form>

{% endblock content %}

ryhom/templates/articles/article-detail.html
{% extends 'boilerplate.html' %}

{% block title %}{{ article.title }} - {{ request.META.HTTP_HOST }}{% endblock title %}
{% block meta_description %}{{ article.summary | slice:':160' }}{% endblock meta_description %}
{% block meta_author %}{{ article.author }}{% endblock meta_author %}

{% block navbar %}
  {% include 'navbar.html' %}
{% endblock navbar %}

{% block content %}

  <p>Categories:
  {% for category in article.categories.all %}
    <a href="{{ category.get_absolute_url }}">{{ category.name }}</a>
  {% endfor %}
  </p>

  <p>Tags:
  {% for tag in article.tags.all %}
    <a href="{% url 'tags:articles_by_tag' tag_slug=tag.slug %}">{{ tag.name }}</a>
  {% endfor %}
  </p>

  <p>Updated on {{ article.modified | date:'M j, Y' }}</p>

  <h1>{{ article.title }}</h1>
  <p>{{ article.summary }}</p>

  {% if article.author.profile_image.url != '' %}
    <img src="{{ article.author.profile_image.url }}" alt="{{ article.author.name }}'s profile image" width="100" height="100"></img>
  {% endif %}
  <p>By <a href="{{ article.author.get_absolute_url }}">{{ article.author }}</a></p>

  {% if article.image.url != '' %}
    <img src="{{ article.image.url }}" alt="Featured image for article, {{ article.title }}" width="800" height="500"></img>
  {% endif %}
  <article>
    {{ article.content | safe }}
  </article>

  {% if user.is_authenticated %}
    <h2>{{ nro_of_comments }} {% if nro_of_comments == 1 %}comment{% else %}comments{% endif %}</h2>
    <form action="" method="POST">
      {% csrf_token %}
      <label for="comment">Type Comment here</label>
      {{ comment_form.comment }}
      <input type="submit" value="Post">
    </form>
  {% else %}
    <h2>{{ nro_of_comments }} {% if nro_of_comments == 1 %}comment{% else %}comments{% endif %} - <a href="{% url 'accounts:login' %}?next={{ request.path }}">Login to comment</a></h2>
  {% endif %}

  {% for comment in comments %}
    {% if comment.is_parent %}
    <p>{{ comment.created | timesince }}</p>
    <h3>{{ comment.author }}</h3>
    <p>{{ comment.comment }}</p>

      <!-- PARENT COMMENT LIKES -->
      <form method="POST" action="{% url 'articles:article_comment_like_unlike' article.pk comment.pk %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ request.path }}">
        <button class="remove-default-btn" type="submit">
          <i>{% if request.user in comment.likers.all %}Unlike{% else %}Like{% endif %}<span> {{ comment.likers.all.count }}</span></i>
        </button>
      </form>
      <!-- PARENT COMMENT LIKES -->

    {% for replies in comment.child_comments %}
      <p>--{{ comment.created | timesince }}</p>
      <h3>--{{ comment.author }}</h3>
      <p>--{{ replies.comment }}</p>

        <!-- CHILD COMMENT LIKES -->
        <form method="POST" action="{% url 'articles:article_comment_like_unlike' article.pk replies.pk %}">
          {% csrf_token %}
          <input type="hidden" name="next" value="{{ request.path }}">
          <button class="remove-default-btn" type="submit">
            <i>{% if request.user in replies.likers.all %}Unlike{% else %}Like{% endif %}<span> {{ replies.likers.all.count }}</span></i>
          </button>
        </form>
        <!-- CHILD COMMENT LIKES -->
    {% endfor %}

    {% if user.is_authenticated %}
      <form action="" method="POST">
        {% csrf_token %}
        <label for="comment">Reply here</label>
        <textarea type="text" name="comment" maxlength="6000"></textarea>
        <input type="hidden" value="{{ comment.pk }}" name="parent">
        <input type="submit" value="Post">
      </form>
    {% endif %}
    {% endif %}
  {% endfor %}

{% endblock content %}

ryhom/templates/articles/delete-article.html
{% extends 'boilerplate.html' %}

{% block title %}Delete {{ article.title }}{% endblock title %}

{% block navbar %}
  {% include 'navbar.html' %}
{% endblock navbar %}

{% block content %}
  <h1>Are You Sure You Want To Delete - {{ article.title }}</h1>

  <form method="POST">
    {% csrf_token %}

    <p>Confirm the deletion of "{{ article.title }}"</p>

    <input type="submit" value="Delete">
    <button type="button" onclick="location.href='{% url 'accounts:my_posts' %}'">Cancel</button>
  </form>
{% endblock %}

ryhom/templates/articles/edit-article.html
{% extends 'boilerplate.html' %}

{% block title %}Edit Article{% endblock title %}

{% block navbar %}
  {% include 'navbar.html' %}
{% endblock navbar %}

{% block content %}
  <h1>Edit Article...</h1>

  {% if messages %}
    {% for message in messages %}
      <p>{{ message | safe }}</p>
    {% endfor %}
  {% endif %}

  <form action="" enctype="multipart/form-data" method="POST">
    {% csrf_token %}

    {% for error in form.non_field_errors %}
      <p>{{ error }}</p>
    {% endfor %}

    {{ form.media }}

    <p>{{ form.title.label_tag }}</p>
    {{ form.title }}
    <p><em>{{ form.title.help_text }}</em></p>
    {{ form.title.errors }}

    <p>{{ form.summary.label_tag }}</p>
    {{ form.summary }}
    <p><em>{{ form.summary.help_text }}</em></p>
    {{ form.summary.errors }}

    <p>{{ form.image.label_tag }}</p>
    {{ form.image }}
    <p><em>{{ form.image.help_text }}</em></p>
    {{ form.image.errors }}

    <p>{{ form.image_credit.label_tag }}</p>
    {{ form.image_credit }}
    <p><em>{{ form.image_credit.help_text }}</em></p>
    {{ form.image_credit.errors }}

    <p>{{ form.content.label_tag }}</p>
    {{ form.content }}
    <p><em>{{ form.content.help_text }}</em></p>
    {{ form.content.errors }}

    <button name="save_for_later" type="submit">Save</button>

    <button name="submit_for_review" type="submit">Submit For Review</button>

  </form>

{% endblock content %}