config/urls.py
"""
Our sitewide URLs
"""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from ryhom.core.views import Error404View

urlpatterns = [
    path('', include('ryhom.core.urls', namespace='core')),
    path('u/', include('ryhom.accounts.urls', namespace='accounts')),
    path('cat/', include('ryhom.categories.urls', namespace='categories')),
    path('tag/', include('ryhom.tags.urls', namespace='tags')),
    path('article/', include('ryhom.articles.urls', namespace='articles')),
    path('post/', include('ryhom.microposts.urls', namespace='microposts')),

    path('/ckeditor/', include('ckeditor_uploader.urls')),
]


# Enable the use of Django admin if "IS_ADMIN_ENABLED" variable is set to true
# If it's false, the Django admin login page shows a 404 page
if settings.IS_ADMIN_ENABLED:
    urlpatterns.append(path('site/ryhom/admin/', admin.site.urls))

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = Error404View.as_view()

ryhom/accounts/urls.py
from django.urls import path

from .views import (AccountSettingsView, ActivateAccountView, ChangeEmailView,
                    ChangePasswordView, LoginUserView, LogoutUserView,
                    RegisterView, ResendActivationEmailView,
                    ResetPasswordConfirmationView, ResetPasswordDoneView,
                    ResetPasswordMessageView, ResetPasswordView, UserPostsView,
                    UserProfileView)

app_name = 'accounts'

urlpatterns = [
    path(
        'auth/create-account',
        RegisterView.as_view(),
        name='create_account'
    ),
    path(
        'auth/activate/<uidb64>/<token>',
        ActivateAccountView.as_view(),
        name='activate'
    ),
    path(
        'auth/resend-activitation-email',
        ResendActivationEmailView.as_view(),
        name='resend_activation_email'
    ),
    path(
        'auth/login',
        LoginUserView.as_view(),
        name='login'
    ),
    path(
        'auth/logout',
        LogoutUserView.as_view(),
        name='logout'
    ),
    path(
        'auth/password-reset',
        ResetPasswordView.as_view(),
        name='password_reset'
    ),
    path(
        'auth/password-reset/message',
        ResetPasswordMessageView.as_view(),
        name='password_reset_message',
    ),
    path(
        'auth/password-reset-confirm/<uidb64>/<token>',
        ResetPasswordConfirmationView.as_view(),
        name='password_reset_confirm'
    ),
    path(
        'auth/password-reset/done',
        ResetPasswordDoneView.as_view(),
        name='password_reset_done',
    ),

    path(
        'account/settings',
        AccountSettingsView.as_view(),
        name='account_settings'
    ),
    path(
        'account/my-posts',
        UserPostsView.as_view(),
        name='my_posts'
    ),
    path(
        '<slug:user_profile_slug>',
        UserProfileView.as_view(),
        name='user_profile'
    ),

    path(
        'account/settings/password/change',
        ChangePasswordView.as_view(),
        name='change_password'
    ),
    path(
        'account/settings/email/change',
        ChangeEmailView.as_view(),
        name='change_email'
    ),
]

ryhom/articles/urls.py
from django.urls import path

from .views import (AddArticleView, AddRemoveArticleCommentLike,
                    ArticleDetailView, DeleteArticleView, EditArticleView)

app_name = 'articles'

urlpatterns = [
    path(
        'add-article',
        AddArticleView.as_view(),
        name='add_article'
    ),
    path(
        'edit-article/<uuid:article_uuid>',
        EditArticleView.as_view(),
        name='edit_article'
    ),
    path(
        'delete-article/<uuid:article_uuid>',
        DeleteArticleView.as_view(),
        name='delete_article'
    ),

    path(
        '<slug:article_slug>',
        ArticleDetailView.as_view(),
        name='article_detail'
    ),
    path(
        '<int:article_pk>/comment/<int:pk>/like',
        AddRemoveArticleCommentLike.as_view(),
        name='article_comment_like_unlike'
    ),
]

ryhom/core/urls.py
from django.urls import path

from .views import IndexView, user_profile_redirect

app_name = 'core'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('profile-redirect', user_profile_redirect),
]

ryhom/microposts/urls.py
from django.urls import path

from .views import (AddMicropostView, AddRemoveMicropostCommentLike,
                    AddRemoveMicropostLike, AllMicropostsListView,
                    DeleteMicropostView, MicropostDetailView)

app_name = 'microposts'

urlpatterns = [
    path('all', AllMicropostsListView.as_view(), name='all_microposts'),
    path('add-post', AddMicropostView.as_view(), name='add_micropost'),
    path(
        'delete-post/<uuid:micropost_uuid>',
        DeleteMicropostView.as_view(),
        name='delete_post'
    ),

    path(
        '<slug:micropost_slug>',
        MicropostDetailView.as_view(),
        name='micropost_detail'
    ),
    path(
        '<int:micropost_pk>/like',
        AddRemoveMicropostLike.as_view(),
        name='micropost_like_unlike'
    ),
    path(
        '<int:micropost_pk>/comment/<int:pk>/like',
        AddRemoveMicropostCommentLike.as_view(),
        name='micropost_comment_like_unlike'
    ),
]

ryhom/tags/urls.py
from django.urls import path

from .views import ArticlesByTagListView, MicropostsByTagListView

app_name = 'tags'

urlpatterns = [
    path(
        'articles/<slug:tag_slug>',
        ArticlesByTagListView.as_view(),
        name='articles_by_tag'
    ),
    path(
        'microposts/<slug:tag_slug>',
        MicropostsByTagListView.as_view(),
        name='microposts_by_tag'
    ),
]

ryhom/accounts/views.py
import socket
from itertools import chain
from operator import attrgetter
from smtplib import SMTPException

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.utils.encoding import force_str
from django.utils.http import urlsafe_base64_decode
from django.views.generic import DetailView, FormView, ListView, View
from django.views.generic.edit import CreateView, UpdateView

from ryhom.articles.models import Article, ArticleComment
from ryhom.core.decorators import confirm_password
from ryhom.core.viewmixins import RedirectAuthenticatedUserMixin
from ryhom.microposts.models import Micropost, MicropostComment

from .forms import (AccountSettingsForm, ChangeEmailForm, ChangePasswordForm,
                    ForgotPasswordForm, LoginForm, RegisterForm,
                    ResendActivationEmailForm, SetNewPasswordForm)
from .models import Account
from .tokens import account_token_generator
from .utils import send_registration_confirm_email

# A list of decorators including our custom decorator -> confirm_password
# that requires the user to insert their password again if there's more
# than, 30 minutes for example, from their last login if they are
# accessing a view with this decorator.
decorators = [login_required, confirm_password]


class RegisterView(RedirectAuthenticatedUserMixin, CreateView):
    form_class = RegisterForm
    template_name = 'accounts/create-account.html'
    success_url = reverse_lazy('accounts:create_account')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False # Deactivate account till it is confirmed
        user.save()

        to_email = form.cleaned_data['email']

        # For all possible send_mail (SMTPException) exceptions...
        # https://docs.python.org/3/library/smtplib.html#smtplib.SMTPException
        try:
            send_registration_confirm_email(self, user, to_email)
            success_message = (f'An account has been created! We\'ve sent \
                                a verification link to <b>{to_email}</b>. \
                                Click it to activate your account!')
            messages.success(self.request, success_message)
        except (SMTPException, socket.gaierror):
            error_message = 'There was an error connecting to the email \
                            server, this is likely our fault. Please try \
                            creating an account later.'
            messages.error(self.request, error_message)

        return super().form_valid(form)


    def form_invalid(self, form):
        error_message = (
            'Error creating the user, please fix the errors below...'
        )
        messages.error(self.request, error_message)
        return super().form_invalid(form)


class ResendActivationEmailView(RedirectAuthenticatedUserMixin, FormView):
    template_name = 'accounts/resend-verification-email.html'
    form_class = ResendActivationEmailForm
    success_url = reverse_lazy('accounts:resend_activation_email')

    def form_valid(self, form):
        email_input = form.cleaned_data['email']
        if Account.objects.filter(email=email_input).exists():
            user = Account.objects.get(email=email_input)
            if not user.is_active:
                self.send_email_to_user(user, email_input)
            else:
                error_message = (
                    'This account has already been activated!'
                )
                messages.warning(self.request, error_message)
        else:
            error_message = (
                'Account with this email doesn\'t exist'
            )
            messages.warning(self.request, error_message)

        return super().form_valid(form)

    def send_email_to_user(self, user, to_email):
        try:
            send_registration_confirm_email(self, user, to_email)
            success_message = (f'A new verification link has been sent to \
                                <b>{to_email}</b>. Click it to activate \
                                your account!')
            response = messages.success(self.request, success_message)
        except (SMTPException, socket.gaierror):
            error_message = 'There was an error connecting to the email \
                            server, this is likely our fault. Please try \
                            resending the verification email later.'
            response = messages.error(self.request, error_message)
        return response


class ActivateAccountView(View):
    def get(self, request, uidb64, token,
            backend='django.contrib.auth.backends.ModelBackend'):
        try:
            uid = force_str(urlsafe_base64_decode(uidb64))
            user = Account.objects.get(pk=uid)
        except (TypeError,
                ValueError,
                OverflowError,
                Account.DoesNotExist):

            user = None

        if user is not None and account_token_generator.check_token(
            user, token):

            user.is_active = True
            user.save()

            if request.user.is_authenticated:
                logout(request)

            login(
                request,
                user,
                backend
            )
            messages.success(request, 'Your email address has been verfied!')
            return redirect(settings.LOGIN_REDIRECT_URL)
        else:
            messages.warning(request, ('The confirmation link was invalid, \
                                possibly because it has already been used.'))
            return redirect(settings.LOGIN_URL)


class LoginUserView(LoginView):
    authentication_form = LoginForm
    template_name = 'accounts/login.html'
    redirect_authenticated_user = settings.LOGIN_REDIRECT_URL


class LogoutUserView(LogoutView):
    def get_next_page(self):
        next_page = super(LogoutUserView, self).get_next_page()
        messages.add_message(
            self.request, messages.SUCCESS,
            "You've successfully logged out!"
        )
        return next_page


@method_decorator(decorators, name='dispatch')
class AccountSettingsView(UpdateView):
    template_name = 'accounts/account-settings.html'
    form_class = AccountSettingsForm
    success_url = reverse_lazy('accounts:account_settings')

    def get_object(self):
        return self.request.user

    def form_valid(self, form):
        messages.success(self.request,
            'Your changes were successfully saved!'
        )
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request,
                    'Unable to make the changes, \
                    fix the errors below and try again.'
        )
        return self.render_to_response(self.get_context_data(form=form))


class UserProfileView(DetailView):
    model = Account
    template_name = 'accounts/user-profile.html'

    def get_object(self):
        self.user = get_object_or_404(
            Account, slug=self.kwargs['user_profile_slug']
        )
        return self.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        user_articles = Article.articles.by_author(
            self.user).published().order_by('-modified')

        user_articles_amount = user_articles.count()

        user_microposts = Micropost.microposts.by_author(
            self.user).published().order_by('-created')

        user_microposts_amount = user_microposts.count()

        # Perhaps here we should also have [:10] after the query???
        user_article_comments = ArticleComment.article_comments.user_comments(self.user)

        user_micropost_comments = MicropostComment.micropost_comments.user_comments(self.user)

        # Let's combine all user comment querysets into one
        # collection of objects --> (WE CAN CHAIN EVEN MORE IF WE WANT TO!)
        # and order them by their creation date + let's show newest comments
        # first with reverse=True
        user_comments = sorted(
            chain(user_article_comments, user_micropost_comments),
            key=attrgetter('created'), reverse=True
        )[:10]

        paginator = Paginator(user_articles, 10)
        page = self.request.GET.get('user-articles-page')
        try:
            user_articles = paginator.page(page)
        except PageNotAnInteger:
            user_articles = paginator.page(1)
        except EmptyPage:
            user_articles = paginator.page(paginator.num_pages)

        paginator = Paginator(user_microposts, 10)
        page = self.request.GET.get('user-microposts-page')
        try:
            user_microposts = paginator.page(page)
        except PageNotAnInteger:
            user_microposts = paginator.page(1)
        except EmptyPage:
            user_microposts = paginator.page(paginator.num_pages)

        context['user_articles'] = user_articles
        context['user_articles_amount'] = user_articles_amount

        context['user_microposts'] = user_microposts
        context['user_microposts_amount'] = user_microposts_amount

        context['user_comments'] = user_comments

        return context


class UserPostsView(LoginRequiredMixin, ListView):

ryhom/categories/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import ListView
from ryhom.articles.models import Article

from .models import Category


class CategoryDetailView(ListView):
    model = Category
    context_object_name = 'articles_in_category'
    template_name = 'categories/category-page.html'
    paginate_by = 2

    def get_queryset(self):
        self.category = get_object_or_404(Category, slug=self.kwargs['category_slug'])
        queryset = Article.articles.published().by_category(self.category)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(CategoryDetailView, self).get_context_data(**kwargs)
        context['category'] = self.category
        return context

ryhom/core/views.py
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import redirect
from django.views import View
from django.views.generic.base import TemplateView
from django.views.generic.edit import UpdateView

from .forms import ConfirmPasswordForm


class IndexView(TemplateView):
    template_name = 'index.html'


class ConfirmPasswordView(UpdateView):
    form_class = ConfirmPasswordForm
    template_name = 'continue-session.html'

    def get_object(self):
        return self.request.user

    def get_success_url(self):
        return self.request.get_full_path()


class Error404View(View):
    def index(self):
        raise Http404


@login_required
def user_profile_redirect(request):
    """
    Used as a dynamic redirect to user's personal profile, because the
    user profile URL requires a slug kwarg, hence, a custom redirect

    settings.py --> LOGIN_REDIRECT_URL
    """
    slug = request.user.slug
    return redirect('accounts:user_profile', user_profile_slug=slug)

ryhom/templates/accounts/account-settings.html
{% extends 'boilerplate.html' %}

{% block title %}Account Settings{% endblock title %}

{% block navbar %}
  {% include 'navbar.html' %}
{% endblock navbar %}

{% block content %}

<h1>Account Settings</h1>

{% if messages %}
  {% for message in messages %}
    <p>{{ message | safe }}</p>
  {% endfor %}
{% endif %}

<form enctype="multipart/form-data" method="POST">
  {% csrf_token %}

  {% for error in form.non_field_errors %}
    <p>{{ error }}</p>
  {% endfor %}

  <h2>Profile Information</h2>

  <p>{{ form.profile_image.label_tag }}</p>
  {% if account.profile_image.url != '' %}
    <img src="{{ account.profile_image.url }}" width="100" height="100"></img>
  {% endif %}
  {{ form.profile_image }}
  <p>{{ form.profile_image.help_text }}</p>
  {{ form.profile_image.errors }}

  <p>{{ form.name.label_tag }}</p>
  {{ form.name }}
  <p>{{ form.name.help_text }}</p>
  {{ form.name.errors }}

  <p>{{ form.gender.label_tag }}</p>
  {{ form.gender }}
  <p>{{ form.gender.help_text }}</p>
  {{ form.gender.errors }}

  <p>{{ form.birthday.label_tag }}</p>
  {{ form.birthday }}
  <p>{{ form.birthday.help_text }}</p>
  {{ form.birthday.errors }}

  <p>{{ form.bio.label_tag }}</p>
  {{ form.bio }}
  <p>{{ form.bio.help_text }}</p>
  {{ form.bio.errors }}

  <p>{{ form.website.label_tag }}</p>
  {{ form.website }}
  <p>{{ form.website.help_text }}</p>
  {{ form.website.errors }}

  <h2>Account Details</h2>

  <p>{{ form.username.label_tag }}</p>
  {{ form.username }}
  <p>{{ form.username.help_text }}</p>
  {{ form.username.errors }}

  <a href="{% url 'accounts:change_email' %}" type="button">Change Email</a>

  <a href="{% url 'accounts:change_password' %}" type="button">Change Password</a>

  <button type="submit">Save Changes</button>
</form>


{% endblock content %}

ryhom/templates/accounts/account-verification-email.html
{% autoescape off %}

Greetings, {{ user.name }}, You're Only A Click Away!

Kindly click the link below given to confirm your registration, to ryhom.com.

(If you can't click this link, please copy and paste it into your browser's address bar.)

http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}

If you think it's not you, just ignore this email.

{% endautoescape %}

ryhom/templates/accounts/change-email.html
{% extends 'boilerplate.html' %}

{% block title %}Change Your Email{% endblock title %}

{% block navbar %}
  {% include 'navbar.html' %}
{% endblock navbar %}

{% block content %}
    <h1>Change Your Account Email</h1>

    {% if messages %}
      {% for message in messages %}
        <p>{{ message | safe }}</p>
      {% endfor %}
    {% endif %}

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <a href="{% url 'accounts:account_settings' %}">&#8592; Back to settings</a>
        <button type="submit">Update Email</button>
    </form>
{% endblock content %}

ryhom/templates/accounts/change-password.html
{% extends 'boilerplate.html' %}

{% block title %}Change Your Password{% endblock title %}

{% block navbar %}
  {% include 'navbar.html' %}
{% endblock navbar %}

{% block content %}
    <h1>Change Your Account Password</h1>

    {% if messages %}
      {% for message in messages %}
        <p>{{ message | safe }}</p>
      {% endfor %}
    {% endif %}

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <a href="{% url 'accounts:account_settings' %}">&#8592; Back to settings</a>
        <button type="submit">Update Password</button>
    </form>
{% endblock content %}

ryhom/templates/accounts/create-account.html
{% extends 'boilerplate.html' %}

{% block title %}Create A Ryhom Account - {{ request.META.HTTP_HOST }}{% endblock title %}

{% block navbar %}
  {% include 'navbar.html' %}
{% endblock navbar %}

{% block content %}

  <h1>Create An Account</h1>

  <p>Or <a href="{% url 'accounts:login' %}">log in</a> to your existing account</p>

    {% if messages %}
      {% for message in messages %}
        <p>{{ message | safe }}</p>
      {% endfor %}
    {% endif %}

  <form action="" method="POST">
    {% csrf_token %}

    {% for error in form.non_field_errors %}
      <p>{{ error }}</p>
    {% endfor %}

    {% for field in form %}
      {{ field.label_tag }}
      <p>{{ field }}</p>
      <p>{{ field.errors }}</p>
      {{ field.help_text }}
    {% endfor %}

    <button type="submit">Create Your Account</button>
  </form>

{% endblock content %}

ryhom/templates/accounts/login.html
{% extends 'boilerplate.html' %}

{% block title %}Log In To Your Account - {{ request.META.HTTP_HOST }}{% endblock title %}

{% block navbar %}
  {% include 'navbar.html' %}
{% endblock navbar %}

{% block content %}

  <h1>Log In</h1>
  <p>Or <a href="{% url 'accounts:create_account' %}">create an account</a> to make your own posts</p>

  {% if messages %}
    {% for message in messages %}
      <p>{{ message | safe }}</p>
    {% endfor %}
  {% endif %}

  {% for key, key_errors in form.errors.as_data.items %}
    {% for error in key_errors %}
      {% if error.code == 'inactive_account' %}
        <p>Your account is still inactive! Click the confirmation link
          sent to your email to activate it, or <a href="{% url 'accounts:resend_activation_email' %}">
          re-send the email</a>.
        </p>
      {% endif %}
    {% endfor %}
  {% endfor %}

  <form action="" method="POST">
    {% csrf_token %}

    {% for error in form.non_field_errors %}
      <p>{{ error }}</p>
    {% endfor %}

    {% for field in form %}
      {{ field.label_tag }}
      <p>{{ field }}</p>
      <p>{{ field.errors }}</p>
      {{ field.help_text }}
    {% endfor %}

    <button type="submit">Log In</button>

    <p><a href="{% url 'accounts:password_reset' %}">Forgot your password?</a></p>
  </form>

{% endblock content %}

ryhom/templates/accounts/password-reset-complete.html
{% extends 'boilerplate.html' %}

{% block content %}
  <p>
    Your password has been set. You may go ahead and <a href="{% url 'accounts:login' %}">login</a> now.
  </p>
{% endblock %}

ryhom/templates/accounts/password-reset-confirm.html
{% extends 'boilerplate.html' %}

{% block content %}

  {% if validlink %}
    <h1>Change password</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Change your password</button>
    </form>
  {% else %}
    <p>
      The password reset link was invalid, possibly because it has already been used.
      Please request a new password reset.
    </p>
  {% endif %}

{% endblock %}

ryhom/templates/accounts/password-reset-done.html
{% extends 'boilerplate.html' %}

{% block content %}

  <p>
    We've emailed you instructions for setting your password, if an account exists with the email you entered.
    You should receive them shortly.
  </p>

  <p>
    If you don't receive an email, please check your spam inbox, or <a href="{% url 'accounts:password_reset' %}">enter your email address again</a>.
  </p>

{% endblock %}

ryhom/templates/accounts/password-reset-email.html
{% autoescape off %}

To initiate the password reset process for your {{ user.get_username }} TestSite Account,
click the link below:

{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

{% endautoescape %}

ryhom/templates/accounts/password-reset.html
{% extends 'boilerplate.html' %}

{% block title %}Reset Your Password{% endblock title %}

{% block navbar %}
  {% include 'navbar.html' %}
{% endblock navbar %}

{% block content %}

  <h1>Reset Your Account Password</h1>

  <p>Enter your details below and we'll send you instructions to reset your password.</p>

  {% if messages %}
    {% for message in messages %}
      <p>{{ message | safe }}</p>
    {% endfor %}
  {% endif %}

  <form method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <a href="{% url 'accounts:login' %}">&#8592; Back to login</a>
      <button type="submit">Send Password Reset Instructions</button>
  </form>

{% endblock content %}

ryhom/templates/accounts/resend-verification-email.html
{% extends 'boilerplate.html' %}

{% block title %}Resend Email Verification{% endblock title %}

{% block navbar %}
  {% include 'navbar.html' %}
{% endblock navbar %}

{% block content %}

  <h1>Resend the email verification link</h1>

  <p>
    We sent you a message with a link to activate your account.
    If you didn't receive it, you can re-enter your email address,
    and we'll send you a new activation link.
  </p>

  {% if messages %}
    {% for message in messages %}
      <p>{{ message | safe }}</p>
    {% endfor %}
  {% endif %}

  <form method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <a href="{% url 'accounts:login' %}">&#8592; Back to login</a>
      <button type="submit">Send Verification Link</button>
  </form>

{% endblock content %}

ryhom/templates/accounts/user-profile.html
{% extends 'boilerplate.html' %}

{% block title %}{{ account.name }} On {{ request.META.HTTP_HOST }}{% endblock title %}
{% block meta_description %}{{ account.bio | slice:':160' }}{% endblock meta_description %}

{% block navbar %}
  {% include 'navbar.html' %}
{% endblock navbar %}

{% block content %}

  {% if messages %}
    {% for message in messages %}
      <p>{{ message | safe }}</p>
    {% endfor %}
  {% endif %}

  <!-- User Profile Info -->
  <h1>{{ account.name }}</h1>
  {% if account.profile_image.url != '' %}
    <img src="{{ account.profile_image.url }}" alt="{{ account.name }}'s profile image" width="300">
  {% endif %}
  <a href="{{ account.website }}" target="_blank">{{ account.website | escape }}<a/>
  <p>Joined {{ account.date_joined | date:'M Y' }}</p>
  {% if account.gender != 'No response' %}
    <p>{{ account.gender }}</p>
  {% endif %}
  <p>{{ account.bio }}</p>
  <!-- End Of User Profile Info -->


  <!-- Articles Published By User -->
  <h2>Published Articles</h2>
  {% if user_articles %}
    {% for article in user_articles %}
      <p>{{ article.title }}</p>
    {% endfor %}
    <!-- End Of Articles Published By User -->

    <!-- User Articles Pagination -->
    {% if user_articles_amount > 10 %}
      <div>
        <span>
          {% if user_articles.has_previous %}
            <a href="?user-articles-page=1">&laquo; first</a>
            <a href="?user-articles-page={{ user_articles.previous_page_number }}">previous</a>
          {% endif %}

          <span>
            Page {{ user_articles.number }} of {{ user_articles.paginator.num_pages }}.
          </span>

          {% if user_articles.has_next %}
            <a href="?user-articles-page={{ user_articles.next_page_number }}">next</a>
            <a href="?user-articles-page={{ user_articles.paginator.num_pages }}">last &raquo;</a>
          {% endif %}
        </span>
      </div>
    {% endif %}
  {% else %}
    {% if account.username == request.user.username %}
      <p>You haven't published any articles yet!</p>
      <a href="{% url 'articles:add_article' %}">Write your first article</a>
    {% else %}
      <p>{{ account.name }} hasn't published any articles yet.</p>
    {% endif %}
  {% endif %}
  <!-- End Of User Articles Pagination -->


  <!-- Microposts Published By User -->
  <h2>Published Microposts</h2>
  {% if user_microposts %}
    {% for micropost in user_microposts %}
      <p>{{ micropost.title }}</p>
    {% endfor %}
  <!-- End Of Microposts Published By User -->

    <!-- User Microposts Pagination-->
    {% if user_microposts_amount > 10 %}
      <div>
        <span>
          {% if user_microposts.has_previous %}
            <a href="?user-microposts-page=1">&laquo; first</a>
            <a href="?user-microposts-page={{ user_microposts.previous_page_number }}">previous</a>
          {% endif %}

          <span>
            Page {{ user_microposts.number }} of {{ user_microposts.paginator.num_pages }}.
          </span>

          {% if user_microposts.has_next %}
            <a href="?user-microposts-page={{ user_microposts.next_page_number }}">next</a>
            <a href="?user-microposts-page={{ user_microposts.paginator.num_pages }}">last &raquo;</a>
          {% endif %}
        </span>
      </div>
    {% endif %}

  {% else %}
    {% if account.username == request.user.username %}
      <p>You haven't published any microposts yet!</p>
      <a href="{% url 'microposts:add_micropost' %}">Write your first micropost</a>
    {% else %}
      <p>{{ account.name }} hasn't published any microposts yet.</p>
    {% endif %}
  {% endif %}
  <!-- End Of User Microposts Pagination -->


  <!-- Comments Published By User -->
  <h2>Recent Comments</h2>
  {% if user_comments %}
    {% for comment in user_comments %}
      <p>{{ comment.comment }}</p>
    {% endfor %}

  {% else %}
    <p>No recent comments found.</p>
  {% endif %}
  <!-- End Of Comments Published By User -->

{% endblock content %}

ryhom/templates/accounts/verification-email.html
{% autoescape off %}

Greetings, {{ user.name }}, You're Only A Click Away!

Kindly click the link below given to confirm your registration, to ryhom.com.

(If you can't click this link, please copy and paste it into your browser's address bar.)

http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}

If you think it's not you, just ignore this email.

{% endautoescape %}